services:
  accounts:
    image: "kanhaiyadocker/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - rajebank
  loans:
    image: "kanhaiyadocker/loans:s5"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - rajebank
  cards:
    image: "kanhaiyadocker/cards:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - rajebank
networks:
  rajebank:
    driver: "bridge"